# Generated by Django 3.1 on 2020-08-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_wiki', models.CharField(max_length=200)),
                ('article_id', models.IntegerField(default=0)),
            ],
        ),
    ]
